language: elm

node_js: '12'

dist: trusty

elm:
  - latest
elm_test: latest
elm_format: latest

cache:
  yarn: true
  directories:
    - node_modules
    - elm_cache_linux
    - elm_cache_osx

env:
  - NODE_ENV=production GAME=ElmImage

os:
  - linux
#  - osx

before_install:
  - if [[ $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push && ! "$GITHUB_TOKEN" ]]; then false; fi
  #Elm cache folders for each OS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ELM_HOME=./elm_cache_linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ELM_HOME=./elm_cache_osx; fi


#before_script:
#  - elm-format --validate . && elm-test #&& elm-test lib/elm-tiled && elm-test lib/elm-image

script:
  - cd examples
  - elm make src/Main.elm --optimize --output=./gh-pages/bundle.min.js
  - cd ..
  - jscodeshift -t transform.js ./examples/gh-pages/bundle.min.js
  - uglifyjs ./examples/gh-pages/bundle.min.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters" --output=./examples/gh-pages/bundle.min.js
#  - prepack ./examples/gh-pages/bundle.min.js --maxStackDepth 1000 --inlineExpressions --out ./examples/gh-pages/bundle.min.js
  - uglifyjs ./examples/gh-pages/bundle.min.js --compress 'keep_fargs=false,unsafe_comps,unsafe' --mangle --output=./examples/gh-pages/bundle.min.js
  - posthtml ./examples/gh-pages/index.html -o ./examples/gh-pages/index.html -c posthtml.config.js

deploy:
  provider: pages:git
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: examples/gh-pages
  on:
    branch: master
  edge: true # opt in to dpl v2
